### ISSUE TITLE
Compile error in cactus_rt: signal_handler.cc

### ISSUE THREAD

**Issue by raulordonezUD** [cactusdynamics/cactus-rt#117]
Hello, first of all thank you for this very helpful code, which I am trying to adapt for a real-time controls application. 

I downloaded cactus_rt and am trying to compile it on Linux Debian 12. When 'make debug' is invoked I receive the following error:

          signal_handler.cc:34:10: error: 'ignore' is not a member of 'std'

Commenting out line 34 allows compilation, but I am confused why the compiler complains about 'ignore'?

Thanks!

-Raul

**Comment by shuhaowu** [comment]
Not sure. Perhaps there's an issue with your compiler. `std::ignore` is a standard since c++11

**Comment by raulordonezUD** [comment]
I found the issue. The following includes are missing from signal_handler.cc <http://signal_handler.cc/>:

#include <iostream>
#include <set>
#include <tuple>

Adding these now compiles without error.
---
Raul Ordonez, PhD
Professor
Nonlinear Control Laboratory
Yaskawa Motoman Robotics Laboratory
Dept. ECE, University of Dayton
Voice: (937) 229-3183   Fax: (937) 229-4529
https://sites.google.com/udayton.edu/raulordonez/welcome

Schedule an appointment with me <https://dayton.starfishsolutions.com/starfish-ops/dl/instructor/serviceCatalog.html?bookmark=connection/816470/schedule>

**Comment by shuhaowu** [comment]
Thanks for reporting this. The include is a bit of a mess last time I checked and depends on a lot of implicit behavior. It really needs to be cleaned up at some point. 

Maybe when we port this library to use C++ modules.

**Comment by raulordonezUD** [comment]
I will be happy to help any way I can. I am currently working on implementing a simple RT control loop for a DC motor, very trivial, but not so simple to do under the RT framework. At least, not for me, since my C++ skills are still very rudimentary.

---
Raul Ordonez, PhD
Professor
Nonlinear Control Laboratory
Yaskawa Motoman Robotics Laboratory
Dept. ECE, University of Dayton
Voice: (937) 229-3183   Fax: (937) 229-4529
https://sites.google.com/udayton.edu/raulordonez/welcome

Schedule an appointment with me <https://dayton.starfishsolutions.com/starfish-ops/dl/instructor/serviceCatalog.html?bookmark=connection/816470/schedule>

**Comment by shuhaowu** [comment]
Ah yeah it should be very simple. Unfortunately the issue is the examples are all very rudimentary and undocumented as the library has undergone some changes. Some of the examples are using practices I don't particularly like either. Let me update the simple example right now so you can maybe use it as a base.

**Comment by shuhaowu** [comment]
I've updated the simple example with a simpler structure and more comments. Maybe this helps. The PR is here: https://github.com/cactusdynamics/cactus-rt/pull/119. You can look at the simple_example now in the code base as I just merged it. https://github.com/cactusdynamics/cactus-rt/blob/master/examples/simple_example/main.cc

If you copy that structure, all you need to do is to fill out the `Loop` method inside the `ExampleRTThread` (although you probably want to rename that). The way I do it is like:

```
bool Loop(int65_t elapsed_ns) noexcept override {
  auto data = ReadEncoder();
  auto output = RunPid(data);
  WriteToMotor(output);
  return false;
}
```

Of course, then in the same `ExampleRTThread` you would have to implement the functions of `ReadEncoder`, `RunPid`, and `WriteToMotor`. 

You can debug with the built-in logger that we have. I have an example with `LOG_INFO_LIMIT`, but in the `Loop` function you an also just use `LOG_INFO(Logger(), "hello world {}", my_value)` as well. 

Hope that helps!
