### ISSUE TITLE
RT FIFO for interprocess communication

### ISSUE THREAD

**Issue by lu-maca** [cactusdynamics/cactus-rt#138]
Hi,

Let's say I have two processes that shall exchange data. Is there a preferred way to implement the inter process communication? 
[This](https://tldp.org/HOWTO/RTLinux-HOWTO-6.html) seems to be the way. 

Are you planning to wrap the real time fifo api in the cactus_rt framework?

Thanks,
Luca

ERRATA CORRIGE: real time fifos were a feature of RTLinux. The main question still remains: is there any preferred way of doing that in preempt_rt patch?

**Comment by lu-maca** [comment]
This paper can be useful: https://ntrs.nasa.gov/api/citations/20200002393/downloads/20200002393.pdf

**Comment by shuhaowu** [comment]
There are many different ways to achieve this. My favourate would be using shm and a lockless ring buffer similar to iceoryx/iceroyx2 does this. That would technically also be more cross platform than using a Linux-specific API.

The second paper is an interesting one. I've read it in the past but it talks more about using network APIs across multiple machines. That's something I've experimented within the past but achieving hard real-time remains quite a challenge.

In any case I do not plan to add any cross-process communication features in cactus-rt. I would look into iceoryx/iceoryx2 if you want to do that.
