### ISSUE TITLE
Compilation error - aarch64

### ISSUE THREAD

**Issue by jagauthier** [cactusdynamics/cactus-rt#147]
I'm trying to build on an ARM board running a custom distribution based on yocto.

I am getting this compilation error:
protos/CMakeFiles/cactus_tracing_embedded_perfetto_protos.dir/build.make:73: *** target pattern contains no '%'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:383: protos/CMakeFiles/cactus_tracing_embedded_perfetto_protos.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

I put this on a raspberry pi, running raspbian, which is also aarch64 and it was able to build.

I did a 'make -n' in build/debug

and discovered it happens with this command:
make -s -f CMakeFiles/Makefile2 all

Any help in troubleshooting this would be great.

**Comment by shuhaowu** [comment]
Hi. I don't think I will be able to help you with this. I build with `cmake --build` and it works with all major distros that I've tested. You can see the CI logs for details. 

Feel free to reopen if there is an issue with the build on a major distro with standard build commands.

**Comment by jagauthier** [comment]
Hey, I compared line 73 with my working copy and there was a big difference.

Working:
protos/trace_packet.pb.h: /usr/bin/protoc

Not working:
protos/trace.pb.h: protos/protobuf::protoc


I think my build didn't get protoc, and maybe it's just not checked for.
